name: Run Gradle Build
on: [push, pull_request, workflow_dispatch]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Java
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        name: Upload packed resourcepack
        with:
          name: Artifact-resourcepack
          path: build/*.zip